### ISSUE TITLE
Use QtPy?

### ISSUE THREAD

**Issue by leha-code** [TheBananaStore/TheBananaClient#6]
TODO:

- [ ] Check if QtPy works on Arch and Fedora.
- [ ] Check Raspbian compaptibilty (@Red-exe-Engineer had issues)

**Comment by Grimet14** [comment]
@leha-code 
Arch and Fedora have python support, so they should have qtpy support...

**Comment by leha-code** [comment]
No. Just because Arch has C++ and mesa support it does not mean it will run
mcpi. In fact it does not run because dependencies are wrong. Same here. We
need to test.

**Comment by Grimet14** [comment]
Ah, ok.

**Comment by leha-code** [comment]
Nope! Never usse QtPy it's cursed! (use curses its less cursed)

**Comment by Bigjango13** [comment]
> Use curses it's less cursed
QtPy is a gui, curses isn't.
